# Generated by Django 5.2.6 on 2026-09-20
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("decks", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cache_key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("theme", models.TextField()),
                ("visual_prompt", models.TextField()),
                ("prompt_json", models.JSONField()),
                ("image", models.ImageField(upload_to="generated/")),
                ("provider", models.CharField(max_length=50)),
                ("prompt_version", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("card", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="decks.card")),
            ],
        ),
        migrations.CreateModel(
            name="GenerationJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("done", "Done"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="pending", max_length=20)),
                ("total_cards", models.PositiveIntegerField()),
                ("completed_cards", models.PositiveIntegerField(default=0)),
                ("failed_cards", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("deck", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="jobs", to="decks.deck")),
            ],
        ),
    ]
