# Generated by Django 5.2.6 on 2026-09-20
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scryfall_id", models.UUIDField(unique=True)),
                ("oracle_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=300)),
                ("mana_cost", models.CharField(blank=True, max_length=100)),
                ("cmc", models.FloatField()),
                ("type_line", models.CharField(max_length=300)),
                ("oracle_text", models.TextField(blank=True)),
                ("flavor_text", models.TextField(blank=True)),
                ("colors", models.JSONField(default=list)),
                ("color_identity", models.JSONField(default=list)),
                ("rarity", models.CharField(max_length=20)),
                ("set_code", models.CharField(max_length=10)),
                ("collector_number", models.CharField(max_length=20)),
                ("original_art_url", models.URLField(blank=True)),
                ("original_artist", models.CharField(blank=True, max_length=200)),
                ("layout", models.CharField(max_length=50)),
                ("scryfall_payload", models.JSONField()),
                ("cached_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Deck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("raw_list", models.TextField()),
                ("theme", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeckCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("raw_name", models.CharField(max_length=300)),
                ("quantity", models.PositiveIntegerField()),
                ("section", models.CharField(choices=[("main", "Main"), ("sideboard", "Sideboard"), ("commander", "Commander")], max_length=20)),
                ("resolution_error", models.CharField(blank=True, max_length=300)),
                ("card", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="decks.card")),
                ("deck", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cards", to="decks.deck")),
            ],
        ),
    ]
